import { BathroomType, Category } from '@/types';

export const bathroomTypes: BathroomType[] = [
  {
    id: '1',
    code: 'FP',
    name: 'Four Piece',
    description: 'Toilet + Sink + Shower + Tub',
    basePrice: 15000,
    imageUrl: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80',
  },
  {
    id: '2',
    code: 'TPS',
    name: 'Three Piece - Shower',
    description: 'Toilet + Sink + Shower',
    basePrice: 13000,
    imageUrl: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&q=80',
  },
  {
    id: '3',
    code: 'TPT',
    name: 'Three Piece - Tub',
    description: 'Toilet + Sink + Tub',
    basePrice: 10000,
    imageUrl: 'https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=800&q=80',
  },
  {
    id: '4',
    code: 'TP',
    name: 'Two Piece',
    description: 'Toilet + Sink',
    basePrice: 4000,
    imageUrl: 'https://images.unsplash.com/photo-1604709177225-055f99402ea3?w=800&q=80',
  },
];

export const mockCategories: Category[] = [
  {
    id: 'cat-1',
    name: 'Demolition',
    description: 'Removal of existing fixtures and materials',
    costCodes: [
      {
        id: 'cc-1',
        code: 'FP-001',
        title: 'Remove existing fixtures',
        description: 'Uninstall and set aside any agreed upon items. Remove existing toilet, shower surround, vanity/sink, bathroom floor tile, mirror(s) and all accessories.',
        unitCost: 500,
        unit: 'each',
        questionType: 'WHITE',
        quantity: 1,
      },
      {
        id: 'cc-2',
        code: 'FP-002',
        title: 'Wall tile removal',
        description: 'Remove tile from walls outside of shower area',
        unitCost: 20,
        unit: 'sqft',
        questionType: 'BLUE',
      },
    ],
  },
  {
    id: 'cat-2',
    name: 'Plumbing',
    description: 'Installation of plumbing fixtures',
    costCodes: [
      {
        id: 'cc-3',
        code: 'FP-010',
        title: 'Install new toilet',
        description: 'Install new toilet in existing location',
        unitCost: 300,
        unit: 'each',
        questionType: 'WHITE',
        quantity: 1,
      },
      {
        id: 'cc-4',
        code: 'FP-011',
        title: 'Relocate shower drain',
        description: 'Move shower drain to new location',
        unitCost: 1400,
        unit: 'each',
        questionType: 'BLUE',
      },
    ],
  },
  {
    id: 'cat-3',
    name: 'Electrical',
    description: 'Electrical work and lighting',
    costCodes: [
      {
        id: 'cc-5',
        code: 'FP-020',
        title: 'Install vanity light',
        description: 'Install new vanity light in existing location',
        unitCost: 200,
        unit: 'each',
        questionType: 'WHITE',
        quantity: 1,
      },
      {
        id: 'cc-6',
        code: 'FP-021',
        title: 'Install recessed cans',
        description: 'Install recessed lighting cans in ceiling',
        unitCost: 150,
        unit: 'each',
        questionType: 'ORANGE',
        dropdownOptions: [
          { label: '6 inch', value: '6' },
          { label: '4 inch', value: '4' },
          { label: '2 inch', value: '2' },
        ],
        minValue: 1,
        maxValue: 6,
      },
    ],
  },
  {
    id: 'cat-4',
    name: 'Tile Installation',
    description: 'Tile work for floors and walls',
    costCodes: [
      {
        id: 'cc-7',
        code: 'FP-030',
        title: 'Install bathroom floor tile',
        description: 'Install new tile on bathroom floor',
        unitCost: 25,
        unit: 'sqft',
        questionType: 'WHITE',
        quantity: 50,
      },
      {
        id: 'cc-8',
        code: 'FP-031',
        title: 'Install wall tile outside shower',
        description: 'Install tile on walls outside of shower area',
        unitCost: 25,
        unit: 'sqft',
        questionType: 'GREEN',
      },
    ],
  },
];
